---
- name: Configure Apache httpd.conf (lineinfile - legacy).
  lineinfile:
    dest: "{{ apache_server_root }}/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  when: item.line is defined
  notify: restart apache

- name: Add apache vhosts configuration.
  template:
    src: "{{ item.template }}"
    dest: "{{ apache_conf_path }}/{{ item.filename }}"
    owner: root
    group: root
    mode: 0644
  with_items: {{ apache_vhosts_config }}
  notify: restart apache
  when: apache_create_vhosts
